name: EncoreUnAutreWorkflow

on: 
  push:
    tags:
      - "*"
    branches:
      - main

jobs:
  deploy-firefox:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: install dependecies
        run: npm i

      - name: build
        run: npm run build:firefox

      - name: Sign with web-ext
        run: |
          npx web-ext sign \
          --api-key ${{ secrets.AMO_JWT_ISSUER }} \
          --api-secret ${{ secrets.AMO_JWT_SECRET }} \
          --channel unlisted \
          --source-dir ./build \
          --artifacts-dir ./signed
          
      - name: create zip
        run: npm run pack:zip

      - name: Upload build artifact
        uses: actions/upload-artifact@v5.0.0         
        with:
          path: ./dist-artifacts
